// Mac's Spice mock-up — products + cart. ponytail: no backend, cart in localStorage, prices are placeholders until the client confirms them.
const PRODUCTS = [
  {id:'original', cat:'shakers', name:'The Original', sub:'BBQ & grill spice rub · 176 g', col:'#E8731A', price:69.90, img:'original',
   blurb:'The one that started it all. A family recipe from the 1960s for roasts, smoking, grilling and everyday cooking.',
   ing:'Salt, sugar, paprika, basil, garlic, black pepper, cayenne pepper, coriander, mustard seed, onion, origanum, anti-caking agent (E551), dextrose, flavour enhancer (MSG), marjoram, parsley, sunflower oil, spice extract, nutmeg.',
   all:'Mustard seed. Made in a facility that also handles wheat, soya, egg, peanut, celery, sesame, mustard and sulphites.'},
  {id:'all-rounder', cat:'shakers', name:'The All-Rounder', sub:'BBQ & grill spice rub · 205 g', col:'#F2B21B', price:69.90, img:'all-rounder',
   blurb:'Chicken, veg, beef. If you only buy one shaker for the braai, buy this one.',
   ing:'Salt, sugar, paprika, garlic, basil, cayenne pepper, coriander, black pepper, mustard seed, onion, dextrose, flavour enhancer (MSG), anti-caking agent (E551), marjoram, parsley, spice extract, sunflower oil, nutmeg.',
   all:'Mustard seed. Made in a facility that also handles wheat, soya, egg, peanut, celery, sesame, mustard and sulphites.'},
  {id:'hot-one', cat:'shakers', name:'The Hot One', sub:'BBQ & grill spice rub with bird\'s eye chilli · 210 g', col:'#D7262B', price:69.90, img:'hot-one',
   blurb:'Bird\'s eye chilli and cumin for spicy chicken, steak, chops and veg. Proper heat, not just colour.',
   ing:'Salt, sugar, chilli, basil, paprika, bird\'s eye chilli, black pepper, cumin, garlic, flavour enhancer (MSG), oregano, anti-caking agent (E551), dextrose, marjoram, spice extract, sunflower oil.',
   all:'Made in a facility that also handles wheat, soya, egg, peanut, celery, sesame, mustard and sulphites.'},
  {id:'zesty-lemon', cat:'shakers', name:'The Zesty Lemon', sub:'BBQ & grill spice rub · 176 g', col:'#8CC63E', price:69.90, img:'zesty-lemon',
   blurb:'Lemon and herbs for fish, veg and chicken on the grill.',
   ing:'Salt, sugar, paprika, basil, garlic, acidity regulator, cayenne pepper, black pepper, coriander, mustard seed, onion, dextrose, origanum, flavour enhancer (MSG), anti-caking agent (E551), marjoram, parsley, spice extract, sunflower oil, lemon extract, nutmeg.',
   all:'Mustard seed. Made in a facility that also handles wheat, soya, egg, peanut, celery, sesame, mustard and sulphites.'},
  {id:'fishermans', cat:'shakers', name:'The Fisherman\'s Blend', sub:'Seafood seasoning · 180 g', col:'#1D9BD1', price:69.90, img:'fishermans',
   blurb:'Four ingredients. Salt, garlic, black pepper, parsley. Made for anything that came out of the sea.',
   ing:'Salt, garlic, black pepper, parsley.',
   all:'None. Packed in a factory that also packs wheat (gluten), soya, cow\'s milk, mustard, celery and sulphites.'},
  {id:'fries', cat:'shakers', name:'Fries & Potatoes', sub:'Air fryer seasoning · 220 g', col:'#8E4DA3', price:69.90, img:'fries',
   blurb:'Paprika, onion and tomato for chips, wedges and roasties. Built for the air fryer.',
   ing:'Salt, dextrose, flavour enhancer (MSG), paprika, onion powder, tomato powder, anti-caking agent (E551), sunflower oil, paprika extract, onion extract, tomato liquid, flavouring.',
   all:'None. Packed in a factory that also packs wheat (gluten), soya, cow\'s milk, mustard, celery and sulphites.'},
  {id:'chicken-bbq', cat:'shakers', name:'Chicken BBQ', sub:'Air fryer seasoning · 220 g', col:'#F08A24', price:69.90, img:'chicken-bbq',
   blurb:'Himalayan and sea salt with paprika and coriander. Any chicken dish, in or out of the air fryer.',
   ing:'Pink Himalayan salt, sea salt, cayenne pepper, paprika, coriander, onion, mustard seed, parsley, sugar, black pepper, nutmeg.',
   all:'Mustard seed. Packed in a factory that also packs wheat (gluten), soya, cow\'s milk, mustard, celery and sulphites.'},
  {id:'roast-veg', cat:'shakers', name:'Roast Veggies', sub:'Air fryer seasoning · 195 g', col:'#4E9B3A', price:69.90, img:'roast-veg',
   blurb:'Sweet peppers, red onion and a touch of chilli for roast and air-fried vegetables.',
   ing:'Salt, garlic, onion, paprika, black pepper, sweet peppers, sugar, red onion, chilli powder, brown vinegar, sweet pepper powder, sunflower oil.',
   all:'None. Packed in a factory that also packs wheat (gluten), soya, cow\'s milk, mustard, celery and sulphites.'},
  {id:'himalayan', cat:'grinders', name:'Himalayan Salt', sub:'Grinder · 390 g', col:'#F0A3B8', price:79.90, img:'himalayan',
   blurb:'Coarse pink Himalayan salt in a refillable grinder.', ing:'Coarse Himalayan pink salt.',
   all:'Packed in a factory that also packs wheat (gluten), soya, cow\'s milk, mustard, celery and sulphites.'},
  {id:'pepper', cat:'grinders', name:'Black Pepper', sub:'Grinder · 170 g', col:'#8A8A90', price:79.90, img:'pepper',
   blurb:'Whole black peppercorns. Grind it fresh.', ing:'Whole black peppercorns.',
   all:'Packed in a factory that also packs wheat (gluten), soya, cow\'s milk, mustard, celery and sulphites.'},
  {id:'sea-salt', cat:'grinders', name:'Sea Salt', sub:'Grinder · 340 g', col:'#7EC8E3', price:79.90, img:'sea-salt',
   blurb:'Coarse Atlantic sea salt in a refillable grinder.', ing:'Coarse Atlantic sea salt.',
   all:'Packed in a factory that also packs wheat (gluten), soya, cow\'s milk, mustard, celery and sulphites.'},
  {id:'chicken-marinade', cat:'sauces', name:'Chicken Marinade', sub:'Marinade & basting sauce · 375 ml', col:'#F08A24', price:49.90, img:'chicken-marinade',
   blurb:'Tomato, apricot and spice. Marinate overnight, baste on the fire.',
   ing:'Water, sugar, tomato paste, salt, apricot jam, modified starch, sunflower oil, acetic acid, seasoning (onion, garlic, herbs, spices, chillies), treacle sugar, sundried peaches and apricots, garlic powder, onion powder, caramel, Worcester sauce powder, preservatives (sodium benzoate, potassium sorbate).',
   all:'Contains sulphites. Produced in a facility that uses cow\'s milk, wheat, gluten, fish, crustaceans, egg and soya.'},
  {id:'steakhouse', cat:'sauces', name:'Steakhouse Marinade', sub:'Marinade & basting sauce · 375 ml', col:'#B8232A', price:49.90, img:'steakhouse',
   blurb:'For all meats and the braai. Darker, richer, a little smoky.',
   ing:'Water, sugar, tomato paste, salt, modified starch, sunflower oil, acetic acid, seasoning (onion, garlic, herbs, spices, chillies), treacle sugar, sundried peaches and apricots, colourants, Worcester sauce powder, preservatives (sodium benzoate, potassium sorbate).',
   all:'Contains sulphites. Produced in a facility that uses cow\'s milk, wheat, gluten, fish, crustaceans, egg and soya.'},
  {id:'s-bbq', cat:'sachets', name:'BBQ Chicken', sub:'Sachet · 20 g', col:'#F08A24', price:12.90, img:'s-bbq', blurb:'One sachet, one chicken. Rub it on, fire it up.', ing:'Ask us for the full ingredient list.', all:'See pack.'},
  {id:'s-peri', cat:'sachets', name:'Peri Peri Chicken', sub:'Sachet · 20 g', col:'#D7262B', price:12.90, img:'s-peri', blurb:'Heat and lemon. The Friday-night one.', ing:'Ask us for the full ingredient list.', all:'See pack.'},
  {id:'s-lemon', cat:'sachets', name:'Lemon & Herb Chicken', sub:'Sachet · 20 g', col:'#C9D43A', price:12.90, img:'s-lemon', blurb:'Mild, fresh, good with everything.', ing:'Ask us for the full ingredient list.', all:'See pack.'},
  {id:'s-paprika', cat:'sachets', name:'Paprika Chicken', sub:'Sachet · 20 g', col:'#E8731A', price:12.90, img:'s-paprika', blurb:'Smoky and sweet.', ing:'Ask us for the full ingredient list.', all:'See pack.'},
  {id:'s-chutney', cat:'sachets', name:'Chutney Chicken', sub:'Sachet · 20 g', col:'#C2318F', price:12.90, img:'s-chutney', blurb:'The Sunday-lunch one.', ing:'Ask us for the full ingredient list.', all:'See pack.'},
  {id:'s-curry', cat:'sachets', name:'Mild Chicken Curry', sub:'Sachet · 20 g', col:'#E0A61C', price:12.90, img:'s-curry', blurb:'Mild enough for the kids.', ing:'Ask us for the full ingredient list.', all:'See pack.'},
];
const DELIVERY = {courier:{label:'Courier, 2–4 working days', fee:99, freeOver:500}, collect:{label:'Collect in Philadelphia, Cape Town', fee:0}};
const WA = '27662218133';

const R = n => 'R' + n.toFixed(2).replace('.', ',');
const byId = id => PRODUCTS.find(p => p.id === id);
const cart = {
  get(){ try { return JSON.parse(localStorage.getItem('mac-cart') || '{}'); } catch(e){ return {}; } },
  set(c){ try { localStorage.setItem('mac-cart', JSON.stringify(c)); } catch(e){} document.dispatchEvent(new Event('cart')); },
  add(id, n=1){ const c = this.get(); c[id] = (c[id] || 0) + n; if (c[id] <= 0) delete c[id]; this.set(c); },
  put(id, n){ const c = this.get(); if (n > 0) c[id] = n; else delete c[id]; this.set(c); },
  clear(){ this.set({}); },
  lines(){ return Object.entries(this.get()).map(([id, n]) => ({p: byId(id), n})).filter(l => l.p); },
  count(){ return this.lines().reduce((s, l) => s + l.n, 0); },
  subtotal(){ return this.lines().reduce((s, l) => s + l.n * l.p.price, 0); },
};
